CREATE DATABASE IF NOT EXISTS CHATBOT_DB;
CREATE SCHEMA IF NOT EXISTS CHATBOT_DB.APP;

USE DATABASE CHATBOT_DB;
USE SCHEMA APP;

CREATE OR REPLACE TABLE CHAT_HISTORY (
  session_id STRING,
  role STRING,
  content STRING,
  ts TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE STAGE APP_STAGE;

CREATE WAREHOUSE IF NOT EXISTS WH_LAB WITH WAREHOUSE_SIZE = 'X-SMALL';
USE WAREHOUSE WH_LAB;


SHOW PARAMETERS LIKE 'CORTEX_ENABLED_CROSS_REGION' IN ACCOUNT;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
